spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: fastDFS
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: huobi
    password: huobi
    url: jdbc:mysql://39.106.217.100/huobi?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  rabbitmq:
    host: 39.106.217.100
    port: 5672
    username: guest
    password: guest
server:
  port: 18082
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true
