spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springcloud
    password: springcloud
    url: jdbc:mysql://39.106.217.100/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  rabbitmq:
    host: 192.168.1.102
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.1.102
    port: 6379
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1
eureka:
  client:
   service-url:
     defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
server:
  port: 8091
env:
  test5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    getProductList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000
# feign开启hystrix
feign:
  hystrix:
    enabled: true
management:
  context-path: /
