spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springcloud
    password: springcloud
    url: jdbc:mysql://39.106.217.100/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.1.102
    port: 5672
    username: guest
    password: guest

server:
  port: 8090
