spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: springcloud
    password: springcloud
    url: jdbc:mysql://39.106.217.100/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    jpa:
      show-sql: true
  redis:
    host: 127.0.0.1
    port: 6379
server:
  port: 8095
